name: Manual destroy including shared infra

on:
  workflow_dispatch:
    inputs:
      targetEnv:
        type: choice
        description: 'targetEnv'
        default: 'nonprod'
        required: true
        options:
          - nonprod
          - prod

run-name: ${{ inputs.targetEnv }} -  - Destroy all environments' stacks, branch=${{ github.head_ref || github.ref_name }}

jobs:
  destroyAllStacks:
    name: Manual destroy everything including the shared infra in one AWS account
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: For prod deployment, only user 'wdaicellorg' can deploy and deployment can only from a release branch
        if: ${{ inputs.targetEnv == 'prod' && !(github.actor == 'wdaicellorg' && startsWith(github.ref_name, 'release')) }}
        run: |
          echo Only user 'wdaicellorg' can deploy to prod, and only the release branch can be deployed to prod.
          exit 1
      - name: Configure AWS Credentials - nonprod
        if: ${{ inputs.targetEnv != 'prod' }}
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ format('arn:aws:iam::{0}:role/github-cdk-deploy-role', secrets.NON_PROD_AWS_ACCOUNT) }}
          aws-region: 'us-east-1'
      - name: Configure AWS Credentials - prod
        if: ${{ inputs.targetEnv == 'prod' }}
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ format('arn:aws:iam::{0}:role/github-cdk-deploy-role', secrets.PROD_AWS_ACCOUNT) }}
          aws-region: 'us-east-1'
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: "16"
      - name: Install AWS CDK
        run: sudo npm install -g aws-cdk

      - name: Destroy everything - all environments including the shared vpcEndpoint, Network Load Balancer, etc.
        run: |
          cd cdk-infra/github-deploy-infra/micro-svc-infra
          npm install
          npm run build

          echo "Destroying all microservices ..."
          cdk destroy "labsys-env-*" --force

          echo "Destroying the shared infrastructure ..."
          cdk destroy labsys-sharedInfra-stack --force


          



        
      
      
      
